#+TITLE: vc-setup-buffer kills local variables
#+SUBTITLE: I love version control and consistency.
#+OPTIONS: num:nil toc:nil

I've stumbled upon inconsistent Emacs behaviour.

I work on many different projects own by different teams of people. They have...

I was trying to setup directory local variable =vc-git-shortlog-switches= to customize VC ChangeLog display, but it wasn't being applied to the buffer. I dug a bit and found that =vc-setup-buffer= calls =kill-all-local-variables=. Commenting out that line fixes my problem. The question is why does it do that?

I tried to look for an answer in the version logs, but there isn't one. =vc-setup-buffer= is introduced here:

#+begin_example
commit 0e362f54037b2f8271c905a39278fa3fa5fc7a1b
Author: Gerd Möllmann <gerd@gnu.org>
Date:   Mon Sep 4 19:46:19 2000 +0000
#+end_example

It already contains the =kill-all-local-variables= call.

Excerpt from the commit message says:

#+begin_example
(vc-setup-buffer): New function, split out of vc-do-command.
#+end_example

But =vc-do-command= did not clear local variables. The only line I found with the call, was in =vc-annotate-mode=:

#+begin_example
-  (kill-all-local-variables)		; Recommended by RMS.
#+end_example

Could it have been a mistake? It's somewhat annoying to not be able to apply directory local variables to VC buffers.

I found a reference to a [[https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44698][bug report]] inside the comment of current implementation of =vc-setup-buffer=. It's about clearing a buffer local variable which is getting updated when visiting change log buffer. From this I gather that the need for clearing buffer local variables comes from the reuse of =*vc-change-log*= buffer. Could we invoke some function in =vc-setup-buffer= which would apply directory local variables on refresh?

After bit of digging I found that =hack-local-variables= is the function I need to call. I've settled with advising the =vc-setup-buffer=:

#+begin_src emacs-lisp
  (defun hack-apply-local-variables-to-current-buffer (&rest ignore)
    (hack-local-variables))

  (advice-add 'vc-setup-buffer :after #'hack-apply-local-variables-to-current-buffer)
#+end_src
